
name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: AlbertHernandez/hello
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm && npm run build
          BUILD_DIR: docs/.vuepress/dist/